project_id = "lichnftmbdhonovtedkp"

[functions.sync-deals]
verify_jwt = false

[functions.image-proxy]
verify_jwt = true

[functions.generate-social-post]
verify_jwt = true

[functions.track-click]
verify_jwt = false